FROM envoyproxy/envoy-dev:latest

RUN apt-get update \
    && apt-get install --no-install-recommends -y tree curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

COPY ./docker-cache-helper.txt .
COPY ./envoy.yaml /etc/envoy.yaml

COPY ./target/wasm32-unknown-unknown/release/hello_wasm.wasm /etc/hello_wasm.wasm
RUN chmod go+r /etc/envoy.yaml
